/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThalamusRouteImport } from './routes/thalamus'
import { Route as SweepRouteImport } from './routes/sweep'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as IndexRouteImport } from './routes/index'

const ThalamusRoute = ThalamusRouteImport.update({
  id: '/thalamus',
  path: '/thalamus',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepRoute = SweepRouteImport.update({
  id: '/sweep',
  path: '/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/sweep': typeof SweepRoute
  '/thalamus': typeof ThalamusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/sweep': typeof SweepRoute
  '/thalamus': typeof ThalamusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops': typeof OpsRoute
  '/sweep': typeof SweepRoute
  '/thalamus': typeof ThalamusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ops' | '/sweep' | '/thalamus'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ops' | '/sweep' | '/thalamus'
  id: '__root__' | '/' | '/ops' | '/sweep' | '/thalamus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsRoute: typeof OpsRoute
  SweepRoute: typeof SweepRoute
  ThalamusRoute: typeof ThalamusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thalamus': {
      id: '/thalamus'
      path: '/thalamus'
      fullPath: '/thalamus'
      preLoaderRoute: typeof ThalamusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweep': {
      id: '/sweep'
      path: '/sweep'
      fullPath: '/sweep'
      preLoaderRoute: typeof SweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsRoute: OpsRoute,
  SweepRoute: SweepRoute,
  ThalamusRoute: ThalamusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
