import { sql } from "drizzle-orm";
import { drizzle, type NodePgDatabase } from "drizzle-orm/node-postgres";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { Pool } from "pg";

import * as schema from "@interview/db-schema";
import { ExplorationRepository } from "../../../src/agent/ssa/explorer/exploration.repository";

const DATABASE_URL =
  process.env.DATABASE_URL ??
  "postgres://thalamus:thalamus@localhost:5433/thalamus";

let pool: Pool;
let db: NodePgDatabase<typeof schema>;
let repo: ExplorationRepository;

async function recreateTempTables(): Promise<void> {
  await db.execute(sql.raw("DROP TABLE IF EXISTS pg_temp.exploration_log"));
  await db.execute(sql.raw(`
    CREATE TEMP TABLE exploration_log (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      query text NOT NULL,
      query_type text NOT NULL,
      signal_source text,
      urls_crawled integer NOT NULL DEFAULT 0,
      items_injected integer NOT NULL DEFAULT 0,
      items_promoted integer NOT NULL DEFAULT 0,
      quality_score real,
      exploration_meta jsonb,
      created_at timestamptz NOT NULL DEFAULT now()
    )
  `));
}

async function seedFixtures(): Promise<void> {
  await db.execute(sql.raw(`
    INSERT INTO exploration_log (
      query,
      query_type,
      signal_source,
      urls_crawled,
      items_injected,
      items_promoted,
      quality_score,
      exploration_meta,
      created_at
    ) VALUES
      ('recent-high', 'web', 'finding', 8, 4, 1, 0.90, '{"urls":["https://a"]}'::jsonb, now() - interval '1 day'),
      ('recent-low', 'market', 'trend', 3, 0, 0, 0.40, '{"urls":["https://b"]}'::jsonb, now() - interval '2 days'),
      ('old-high', 'academic', 'archive', 2, 1, 0, 0.95, '{"urls":["https://c"]}'::jsonb, now() - interval '45 days')
  `));
}

beforeAll(async () => {
  pool = new Pool({ connectionString: DATABASE_URL, max: 1 });
  db = drizzle<typeof schema>(pool, { schema });
  repo = new ExplorationRepository(db);
});

beforeEach(async () => {
  await recreateTempTables();
  await seedFixtures();
});

afterAll(async () => {
  await pool.end();
});

describe("ExplorationRepository", () => {
  it("creates a new exploration log row", async () => {
    const row = await repo.create({
      query: "new-query",
      queryType: "web",
      signalSource: "manual",
      urlsCrawled: 5,
      itemsInjected: 2,
      itemsPromoted: 1,
      qualityScore: 0.7,
      explorationMeta: { urls: ["https://new"] },
    });

    expect(row).toMatchObject({
      query: "new-query",
      queryType: "web",
      signalSource: "manual",
      urlsCrawled: 5,
      itemsInjected: 2,
      itemsPromoted: 1,
      qualityScore: 0.7,
      explorationMeta: { urls: ["https://new"] },
    });
  });

  it("findRecent returns newest rows first and honors the limit", async () => {
    const rows = await repo.findRecent(2);

    expect(rows.map((row) => row.query)).toEqual(["recent-high", "recent-low"]);
  });

  it("findHighQuality filters above the threshold and sorts by quality descending", async () => {
    const rows = await repo.findHighQuality(0.8, 10);

    expect(rows.map((row) => row.query)).toEqual(["old-high", "recent-high"]);
  });

  it("getStats aggregates only rows within the requested time window", async () => {
    const stats = await repo.getStats(30);

    expect(stats.total_explorations).toBe(2);
    expect(stats.total_urls).toBe(11);
    expect(stats.total_injected).toBe(4);
    expect(stats.total_promoted).toBe(1);
    expect(Number(stats.avg_quality)).toBeCloseTo(0.65, 2);
  });
});
