/**
 * SSA vocabulary — keywords for domainRelevance filtering.
 *
 * Consumed by the kernel via DomainConfig.keywords. Adding a new domain
 * (e.g. threat-intel) means creating a sibling file with that domain's
 * keyword set — the kernel itself never changes.
 */

export const SSA_KEYWORDS: Set<string> = new Set([
  // Core objects.
  "satellite",
  "satellites",
  "spacecraft",
  "payload",
  "bus",
  "debris",
  "object",
  "rocket",
  "stage",
  "upper-stage",
  "constellation",
  "fleet",
  "rideshare",
  // Orbits & elements.
  "orbit",
  "orbital",
  "leo",
  "meo",
  "geo",
  "gto",
  "heo",
  "sso",
  "lunar",
  "cislunar",
  "apogee",
  "perigee",
  "inclination",
  "raan",
  "eccentricity",
  "epoch",
  "tle",
  "omm",
  "ephemeris",
  "ephemerides",
  "propagation",
  "sgp4",
  // Operations & events.
  "conjunction",
  "collision",
  "maneuver",
  "manoeuvre",
  "burn",
  "delta-v",
  "deltav",
  "station-keeping",
  "deorbit",
  "reentry",
  "fragmentation",
  "breakup",
  "kessler",
  "close-approach",
  // Sensing & provenance.
  "radar",
  "optical",
  "tracking",
  "observation",
  "celestrak",
  "space-track",
  "spacetrack",
  "noaa",
  "esa",
  "nasa",
  "cneos",
  "operator",
  "launch",
  "mission",
  "telemetry",
  "advisory",
  "warning",
  "catalog",
  "cosmos",
  "norad",
  // Adjacent context.
  "earth-observation",
  "remote-sensing",
  "comms",
  "communications",
  "sigint",
  "gnss",
  "gps",
  "galileo",
  "glonass",
  "beidou",
  "starlink",
  "oneweb",
  "kuiper",
  "iridium",
]);
